#include"StdAfx.h"
#include".\officialvirtualsemanticdictionary.h"

using namespace SS::Core::Features;

namespace SS
{
namespace Semantic
{
namespace VirtualDictionaries
{


	COfficialVirtualSyntaxDictionary::COfficialVirtualSyntaxDictionary(void)
	{
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"along",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceFixedPoint	)));	
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"abaft",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceEnd	)));	
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"aboard",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceEnd,Values::SyntaxCategories.scAjunctPlaceFixedPoint	)));	
	//	m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"about",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	semtTimeFrequency	)));	
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"above",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceEnd,Values::SyntaxCategories.scAjunctPlaceFixedPoint	)));	
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"across",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceEnd,Values::SyntaxCategories.scAjunctPlaceFixedPoint	)));	
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"after",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctTimeFixedPoint	)));	
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"against",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceEnd,Values::SyntaxCategories.scAjunctPlaceFixedPoint	)));	
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"ahead",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceEnd,Values::SyntaxCategories.scAjunctPlaceFixedPoint	)));	
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"along",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceEnd,Values::SyntaxCategories.scAjunctPlaceFixedPoint	)));	
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"alongside",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceEnd,Values::SyntaxCategories.scAjunctPlaceFixedPoint	)));	
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"amid"	,COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceEnd,Values::SyntaxCategories.scAjunctPlaceFixedPoint	)));	
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"amidst",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceFixedPoint,Values::SyntaxCategories.scAjunctPlaceEnd	)));	
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"among",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceFixedPoint,Values::SyntaxCategories.scAjunctPlaceEnd	)));	
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"amongst",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceFixedPoint,Values::SyntaxCategories.scAjunctPlaceEnd	)));	
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"apres",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctTimeSource	)));	
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"around",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceEnd,Values::SyntaxCategories.scAjunctPlaceFixedPoint,Values::SyntaxCategories.scAjunctTimeFixedPoint	)));	
	//	m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"as"	,COfficialVirtualSyntaxDictionary::SSyntaxCategories(	semtCause	)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"astraddle",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceFixedPoint,Values::SyntaxCategories.scAjunctPlaceEnd	)));	
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"at"	,COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctTimeFixedPoint,Values::SyntaxCategories.scAjunctPlaceEnd	,Values::SyntaxCategories.scAjunctPlaceFixedPoint)));	
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"athwart",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceFixedPoint,Values::SyntaxCategories.scAjunctPlaceEnd	)));	
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"atop"	,COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceFixedPoint,Values::SyntaxCategories.scAjunctPlaceEnd	)));	
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"away from",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceFixedPoint,Values::SyntaxCategories.scAjunctPlaceSource	)));	
	//	m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"because of",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	semtCause	)));	
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"before",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctTimeFixedPoint	)));	
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"behind",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceFixedPoint,Values::SyntaxCategories.scAjunctPlaceEnd	)));	
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"below",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceFixedPoint,Values::SyntaxCategories.scAjunctPlaceEnd	)));	
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"ben"	,COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceFixedPoint,Values::SyntaxCategories.scAjunctPlaceEnd	)));	
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"beneath",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceFixedPoint,Values::SyntaxCategories.scAjunctPlaceEnd	)));	
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"beside",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceFixedPoint,Values::SyntaxCategories.scAjunctPlaceEnd	)));	
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"between",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceEnd,Values::SyntaxCategories.scAjunctPlaceFixedPoint,Values::SyntaxCategories.scAjunctTimeFixedPoint)));	
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"betwixt",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceFixedPoint,Values::SyntaxCategories.scAjunctPlaceEnd	)));	
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"beyond",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceEnd,Values::SyntaxCategories.scAjunctPlaceFixedPoint	)));	
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"by"	,COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctTimeFixedPoint , Values::SyntaxCategories.scAjunctTimeEnd, Values::SyntaxCategories.scAjunctPlaceFixedPoint)));	
		//m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"by means of",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	semtInstrument	)));	
		//m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"by way of",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	semtInstrument	)));	
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"chez"	,COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceFixedPoint,Values::SyntaxCategories.scAjunctPlaceEnd	)));	
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"close to",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceFixedPoint,Values::SyntaxCategories.scAjunctPlaceEnd	)));	
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"cross",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceFixedPoint,Values::SyntaxCategories.scAjunctPlaceEnd	)));	
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"down"	,COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceFixedPoint,Values::SyntaxCategories.scAjunctPlaceEnd	)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"down to",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceFixedPoint,Values::SyntaxCategories.scAjunctPlaceEnd	)));	
	//	m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"due to",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	semtCause	)));	
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"during",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctTimeDuration	)));	
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"ferninst",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceFixedPoint,Values::SyntaxCategories.scAjunctPlaceEnd	)));	
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"following",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctTimeFixedPoint	)));	
	//	m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"for",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	PURPOSE	)));	
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"for"	,COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctTimeDuration	)));	
	//	m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"for the sake of",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	PURPOSE	)));	
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"fore"	,COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctTimeFixedPoint	)));	
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"fornent",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceFixedPoint,Values::SyntaxCategories.scAjunctPlaceEnd	)));	
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"forth from",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceSource	)));	
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"frae"	,COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceSource	)));	
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"fro"	,COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceSource	)));	
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"from"	,COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceSource,Values::SyntaxCategories.scAjunctTimeSource	)));	
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"further to",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceFixedPoint,Values::SyntaxCategories.scAjunctPlaceEnd	)));	
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"gainst",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceFixedPoint,Values::SyntaxCategories.scAjunctPlaceEnd	)));	
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"in"	,COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctTimeFixedPoint,Values::SyntaxCategories.scAjunctPlaceEnd,Values::SyntaxCategories.scAjunctPlaceFixedPoint	)));	
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"in front of",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceFixedPoint,Values::SyntaxCategories.scAjunctPlaceEnd	)));	
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"inside",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceFixedPoint,Values::SyntaxCategories.scAjunctPlaceEnd	)));	
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"into",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceEnd	)));	
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"mid"	,COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceFixedPoint,Values::SyntaxCategories.scAjunctPlaceEnd	)));	
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"midst",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceFixedPoint,Values::SyntaxCategories.scAjunctPlaceEnd	)));	
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"near",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceFixedPoint,Values::SyntaxCategories.scAjunctTimeFixedPoint	)));	
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"neath",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceFixedPoint,Values::SyntaxCategories.scAjunctPlaceEnd	)));	
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"next to",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceFixedPoint,Values::SyntaxCategories.scAjunctPlaceEnd	)));	
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"nigh"	,COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceFixedPoint,Values::SyntaxCategories.scAjunctPlaceEnd	)));	
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"off"	,COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceSource	)));		
	//	m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"on",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	CONDITION	)));	
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"on"	,COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctTimeFixedPoint,Values::SyntaxCategories.scAjunctPlaceEnd,Values::SyntaxCategories.scAjunctCause,Values::SyntaxCategories.scAjunctPlaceFixedPoint	)));	
	//	m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"on grounds of",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	semtCause	)));	
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"on top of",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceEnd,Values::SyntaxCategories.scAjunctPlaceFixedPoint	)));	
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"onto"	,COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceEnd	)));	
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"opposite",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceEnd,Values::SyntaxCategories.scAjunctPlaceFixedPoint	)));	
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"out of",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceSource	, Values::SyntaxCategories.scAjunctPlaceFixedPoint)));	
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"outside",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceFixedPoint,Values::SyntaxCategories.scAjunctPlaceEnd	)));	
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"outside of",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceFixedPoint,Values::SyntaxCategories.scAjunctPlaceEnd	)));	
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"over"	,COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceEnd,Values::SyntaxCategories.scAjunctPlaceFixedPoint	)));	
	//	m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"owing to",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	semtCause	)));	
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"past"	,COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctTimeFixedPoint	)));	
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"pending",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctTimeDuration	)));	
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"prior to",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctTimeFixedPoint	)));	
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"round",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceEnd,	Values::SyntaxCategories.scAjunctPlaceFixedPoint)));	
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"since",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctTimeSource	)));	
	//	m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"sith"	,COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctTimeSource	)));	
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"starting with",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctTimeSource	)));	
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"subsequent to",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctTimeFixedPoint	)));	
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"syne"	,COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctTimeSource	)));	
	//	m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"thanks to",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	semtCause	)));	
	//	m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"through",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	semtInstrument	)));	
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"through",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctTimeDuration	)));	
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"throughout",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctTimeDuration , Values::SyntaxCategories.scAjunctPlaceFixedPoint	)));	
	//	m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"thwart",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceEnd,	Values::SyntaxCategories.scAjunctPlaceFixedPoint)));	
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"till"	,COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctTimeEnd	)));	
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"to"	,COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceEnd, Values::SyntaxCategories.scAjunctTimeEnd	)));	
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"toward",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceEnd, Values::SyntaxCategories.scAjunctTimeEnd)));		
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"towards",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceEnd,	Values::SyntaxCategories.scAjunctTimeEnd)));	
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"twixt",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceEnd,	Values::SyntaxCategories.scAjunctPlaceFixedPoint)));	
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"under",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceEnd,Values::SyntaxCategories.scAjunctPlaceFixedPoint	)));	
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"until",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctTimeEnd	)));	
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"unto"	,COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctTimeEnd	)));	
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"upon"	,COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceFixedPoint,Values::SyntaxCategories.scAjunctPlaceEnd	)));	
	//	m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"with"	,COfficialVirtualSyntaxDictionary::SSyntaxCategories(	semtInstrument	)));	
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"within",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctTimeDuration,Values::SyntaxCategories.scAjunctPlaceFixedPoint	)));	
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"every",COfficialVirtualSyntaxDictionary::SSyntaxCategories(Values::SyntaxCategories.scAjunctTimeFixedPoint)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"each",COfficialVirtualSyntaxDictionary::SSyntaxCategories(Values::SyntaxCategories.scAjunctTimeFixedPoint)));
	/////////////////////русские предлоги
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"близ",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceFixedPoint , Values::SyntaxCategories.scAjunctTimeFixedPoint)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"в",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceFixedPoint , Values::SyntaxCategories.scAjunctPlaceEnd , Values::SyntaxCategories.scAjunctTimeFixedPoint)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"в глубь ",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceEnd)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"в направлении",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceEnd)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"в направлении к",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceEnd)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"в направлении ко",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceEnd)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"в отдалении от",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceFixedPoint)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"в предвидении",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctTimeFixedPoint)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"в предвкушении",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctTimeFixedPoint)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"в преддверии ",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctTimeFixedPoint)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"в продолжение",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctTimeDuration)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"в процессе",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctTimeDuration)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"в районе",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceFixedPoint)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"в рамках",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceFixedPoint)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"в стороне от",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceFixedPoint)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"в сторону",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceEnd)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"в течение",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctTimeDuration)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"в ходе ",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctTimeDuration)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"вблизи",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceFixedPoint)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"вблизи от",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceFixedPoint)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"вдалеке от",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceFixedPoint)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"вдали от",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceFixedPoint)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"вдоль",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceFixedPoint , Values::SyntaxCategories.scAjunctPlaceEnd)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"вдоль по",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceFixedPoint , Values::SyntaxCategories.scAjunctPlaceEnd)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"вне",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceFixedPoint , Values::SyntaxCategories.scAjunctTimeFixedPoint)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"внутри",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceFixedPoint)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"внутрь",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceEnd)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"во",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceFixedPoint , Values::SyntaxCategories.scAjunctPlaceEnd , Values::SyntaxCategories.scAjunctTimeFixedPoint)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"во время",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctTimeDuration)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"вовнутрь",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceEnd)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"возле",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceFixedPoint)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"вокруг",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceFixedPoint)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"вперед",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceFixedPoint)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"впереди",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceFixedPoint)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"вплоть до",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceEnd , Values::SyntaxCategories.scAjunctTimeEnd)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"впредь до",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctTimeEnd)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"вслед",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceEnd)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"вслед за",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceEnd)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"выше",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceFixedPoint)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"до",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceEnd , Values::SyntaxCategories.scAjunctTimeEnd , Values::SyntaxCategories.scAjunctTimeDuration)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"за",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceFixedPoint , Values::SyntaxCategories.scAjunctTimeDuration)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"за пределами",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceFixedPoint)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"за пределы",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceEnd)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"из",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceSource)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"из пределов",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceSource)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"из-за",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceSource)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"изо ",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceSource)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"из-под",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceSource)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"из-подо",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceSource)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"к",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceEnd , Values::SyntaxCategories.scAjunctTimeEnd)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"ко",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceEnd , Values::SyntaxCategories.scAjunctTimeEnd)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"меж",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceFixedPoint , Values::SyntaxCategories.scAjunctTimeFixedPoint)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"между",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceFixedPoint , Values::SyntaxCategories.scAjunctTimeFixedPoint)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"мимо",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceFixedPoint)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"на",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceEnd , Values::SyntaxCategories.scAjunctTimeFixedPoint , Values::SyntaxCategories.scAjunctPlaceFixedPoint)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"на протяжении",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctTimeDuration)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"на пути",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceEnd)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"на пути к",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceEnd)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"на путях",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceEnd)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"на путях к",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceEnd)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"над",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceFixedPoint)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"надо",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceFixedPoint)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"накануне",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctTimeFixedPoint)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"напротив",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceFixedPoint)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"наравне с",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceFixedPoint)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"наравне со",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceFixedPoint)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"насупротив",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceFixedPoint)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"начиная",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctTimeSource)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"начиная от",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctTimeSource)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"начиная с",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctTimeSource , Values::SyntaxCategories.scAjunctPlaceSource)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"начиная со",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctTimeSource , Values::SyntaxCategories.scAjunctPlaceSource)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"невдалеке от",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceFixedPoint)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"недалеко от",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceFixedPoint)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"неподалеку от",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceFixedPoint)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"ниже",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceFixedPoint)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"обок",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceFixedPoint)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"около",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceFixedPoint)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"окрест",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceFixedPoint)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"от",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceSource , Values::SyntaxCategories.scAjunctTimeSource)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"ото",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceSource , Values::SyntaxCategories.scAjunctTimeSource)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"перед",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceFixedPoint , Values::SyntaxCategories.scAjunctTimeFixedPoint)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"передо",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceFixedPoint , Values::SyntaxCategories.scAjunctTimeFixedPoint)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"по",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceFixedPoint , Values::SyntaxCategories.scAjunctTimeFixedPoint, Values::SyntaxCategories.scAjunctTimeEnd)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"по истечении",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctTimeFixedPoint)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"по направлению",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceEnd)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"по направлению к",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceEnd)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"по направлению ко",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceEnd)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"по прошествии",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctTimeFixedPoint)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"поблизости",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceFixedPoint)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"поблизости от",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceFixedPoint)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"поверх",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceFixedPoint)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"под",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceFixedPoint)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"подле",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceFixedPoint)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"подо",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceFixedPoint)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"позади",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceFixedPoint)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"по-над",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceFixedPoint)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"поодаль от",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceFixedPoint)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"посереди",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceFixedPoint , Values::SyntaxCategories.scAjunctTimeFixedPoint)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"посередине",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceFixedPoint , Values::SyntaxCategories.scAjunctTimeFixedPoint)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"после",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctTimeFixedPoint)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"посреди",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceFixedPoint , Values::SyntaxCategories.scAjunctTimeFixedPoint)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"посредине",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceFixedPoint , Values::SyntaxCategories.scAjunctTimeFixedPoint)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"пред",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceFixedPoint , Values::SyntaxCategories.scAjunctTimeFixedPoint)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"предо",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceFixedPoint , Values::SyntaxCategories.scAjunctTimeFixedPoint)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"прежде",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctTimeFixedPoint)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"при",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceFixedPoint , Values::SyntaxCategories.scAjunctTimeFixedPoint)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"промеж",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceFixedPoint , Values::SyntaxCategories.scAjunctTimeFixedPoint)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"промежду",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceFixedPoint , Values::SyntaxCategories.scAjunctTimeFixedPoint)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"против",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceFixedPoint)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"рядом с",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceFixedPoint)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"рядом со",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceFixedPoint)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"с",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceSource , Values::SyntaxCategories.scAjunctTimeSource , Values::SyntaxCategories.scAjunctPlaceFixedPoint)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"сбоку от",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceFixedPoint)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"сверх",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceFixedPoint)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"сверху",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceFixedPoint)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"сзади",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceFixedPoint)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"сквозь",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceFixedPoint)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"следом за",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceEnd)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"снаружи",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceFixedPoint)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"снизу",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceFixedPoint)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"со",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceSource , Values::SyntaxCategories.scAjunctTimeSource , Values::SyntaxCategories.scAjunctPlaceFixedPoint)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"со стороны",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceSource)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"спереди",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceFixedPoint)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"среди",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceFixedPoint , Values::SyntaxCategories.scAjunctTimeFixedPoint)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"средь",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceFixedPoint , Values::SyntaxCategories.scAjunctTimeFixedPoint)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"у",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctPlaceFixedPoint)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"через",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctTimeFixedPoint)));
		m_PrepositionSyntaxTable.insert(COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::value_type(L"чрез",COfficialVirtualSyntaxDictionary::SSyntaxCategories(	Values::SyntaxCategories.scAjunctTimeFixedPoint)));
	}

	COfficialVirtualSyntaxDictionary::~COfficialVirtualSyntaxDictionary(void)
	{
	}

	bool COfficialVirtualSyntaxDictionary::GetByFormPrepositionSyntaxCategories(std::wstring* pwsWord, list<SS::Core::Features::Types::SyntaxCategories> * plSyntaxCategories)
	{
		if ( pwsWord==NULL || plSyntaxCategories==NULL || pwsWord->size()==0) 
			return false;

		COfficialVirtualSyntaxDictionary::TSyntaxCategoriesTable::iterator itResult;
		plSyntaxCategories->clear();

		itResult=m_PrepositionSyntaxTable.find(*pwsWord);
		if ( itResult==m_PrepositionSyntaxTable.end() )
			return false;
		
		plSyntaxCategories->assign(itResult->second.m_SyntaxCategories.begin(),itResult->second.m_SyntaxCategories.end());
		return true;
	}

	bool COfficialVirtualSyntaxDictionary::IsPrepositionSyntaxExist(std::wstring* pwsWord )
	{
		if ( pwsWord==NULL || pwsWord->size()==0) 
			return false;		
		
		return m_PrepositionSyntaxTable.find(*pwsWord)!=m_PrepositionSyntaxTable.end();

		return false;
	}

}
}
}